{% set version = "1.3.3" %}

package:
  name: ipycytoscape
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipycytoscape/ipycytoscape-{{ version }}.tar.gz
  sha256: b6f3199df034f088e92d388e27e629f58ae2901b213cb9299e5b564272f9a2f8

build:
  number: 1
  script:
    - npm install --save --dev "@jupyterlab/builder@3.4.6"
    - {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - jupyter-packaging >=0.7.0,<0.8.0
    - jupyterlab >=3,<4
    - nodejs >=16,<17
    - pip
    - python >=3.7
  run:
    - ipywidgets >=7.6.0
    - python >=3.7
    - spectate

test:
  imports:
    - ipycytoscape
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter nbextension list
    - jupyter nbextension list 1>nbextensions 2>&1
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "jupyter-cytoscape.*OK" labextensions || exit 1
    - grep -iE "jupyter-cytoscape/extension.*enabled" nbextensions || exit 1
  requires:
    - pip
    - nbclassic
    - jupyterlab >=3,<4

about:
  home: https://github.com/QuantStack/ipycytoscape
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - ipycytoscape/labextension/static/third-party-licenses.json
  summary: Python implementation of the graph visualization tool Cytoscape

extra:
  recipe-maintainers:
    - marimeireles
    - martinRenou
    - SylvainCorlay
    - rmorshea
    - ianhi
